### PR TITLE
Fix Builds on MacOS

### LINKED ISSUE #257: Failing builds on MacOS
@tanishqaggarwal reported this build issue on MacOS:
```
(venv) ➜  psim git:(master) bazel test //test/psim:all
INFO: Analyzed 2 targets (14 packages loaded, 12607 targets configured).
INFO: Found 2 test targets...
ERROR: /Users/tanishqaggarwal/Documents/pan/repositories/psim/BUILD.bazel:55:26: C++ compilation of rule '//:psim_truth' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' -iquote . -iquote ... (remaining 38 argument(s) skipped)
Use --sandbox_debug to see verbose messages from the sandbox
In file included from src/psim/truth/time.cpp:25:
In file included from include/psim/truth/time.hpp:32:
bazel-out/darwin-fastbuild/bin/include/psim/truth/time.yml.hpp:45:58: error: use 'template' keyword to treat 'get' as a dependent template name
    prefix_t_ns(_prefix+".t.ns", config[_prefix+".t.ns"].get<Integer>()),
                                                         ^
bazel-out/darwin-fastbuild/bin/include/psim/truth/time.yml.hpp:47:61: error: use 'template' keyword to treat 'get' as a dependent template name
    prefix_dt_ns(_prefix+".dt.ns", config[_prefix+".dt.ns"].get<Integer>()),
                                                            ^
2 errors generated.
INFO: Elapsed time: 41.799s, Critical Path: 17.27s
INFO: 46 processes: 46 darwin-sandbox.
FAILED: Build did NOT complete successfully
//test/psim:core_test                                                 NO STATUS
//test/psim:truth_test                                          FAILED TO BUILD
FAILED: Build did NOT complete successfully
```
Going to update the calls to `get` to keep apple clang happy for the time being.

### PR DESCRIPTION
**Pull request by kylekrol**
Fixes #257.

## Summary of Changes

* Update lin pointer to include compatibility fixes.
* Include the `template` keyword on calls to `get<...>`, `cast<...>`, et cetera.

### CODE REVIEW

File: test/psim/core/configuration_test.cpp [hunk 1]
```diff
@@ -34,7 +34,7 @@ TEST(Configuration, TestGet) {
   auto const config = psim::Configuration::make(file);
 
   // Test a proper access
-  ASSERT_EQ(config.get("test.integer")->get<psim::Integer>(), 1);
+  ASSERT_EQ(config.get("test.integer")->template get<psim::Integer>(), 1);
```
Comment (tanishqaggarwal) [inline test/psim/core/configuration_test.cpp:37]: Why is this valid C++? I'm confused by the syntax (why is the space between template and get allowed?)

**Review by tanishqaggarwal — APPROVED** [review]
Works for me now!

File: test/psim/core/configuration_test.cpp (hunk 1 above)
Comment (kylekrol) [reply test/psim/core/configuration_test.cpp:37]: That's how the `template` and `typename` keywords are actually intended to work. Here's a cool explanation about why the parser requires them: https://stackoverflow.com/questions/610245/where-and-why-do-i-have-to-put-the-template-and-typename-keywords

Essentially though, they're required sometimes to fix ambiguity. Although in this case it seems only apple clang was complaining on not GCC.
